name = "ExampleJuggler"
uuid = "3bbe58f8-ed81-4c4e-a134-03e85fcf4a1a"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "0.8,0.9"
Literate = "2"
julia = "1.9"
Test = "1.9"
